services:
  backend:
    command: npm run dev
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
      target: development-dependencies-env
    command: npm run dev -- --host 0.0.0.0 --port 5173
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  backend_node_modules:
  frontend_node_modules:
